name: Doxygen Action

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Doxygen Action
      uses: mattnotmitt/doxygen-action@v1.9.5
      with:
        # Path to Doxyfile
        doxyfile-path: "./Doxyfile" # default is ./Doxyfile
        # Working directory
        working-directory: "."

    - name: Deploy
      uses: actions/upload-artifact@v3
      with:
        name: html
        path: ./html